### ISSUE TITLE
storeTree doesn't return success or failure

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/starlasu-lionweb-repository-client#12]
Storing a tree can fail for a number of reasons (e.g. unsupported characters in the node ID) but it appears like it returns OK even when the HTTP request fails.

**Comment by ftomassetti** [comment]
This is now being fixed in the branch where I introduce functional tests

**Comment by ftomassetti** [comment]
We need to provide an example (as a functional test), and to deal with the logic for appending trees

**Comment by ftomassetti** [comment]
Done
