### ISSUE TITLE
KolasuClient.getNode way too slow

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/starlasu-lionweb-repository-client#23]
Its internal `adjustSource` function will call `lionWebClient.getAncestorsId(nodeID)` often, resulting in thousands of HTTP calls to the Lionweb repo. For medium sized trees this already results in a wait of several seconds; for bigger trees, I stopped waiting after minutes.

**Comment by ftomassetti** [comment]
The good news is that in the branch under development (https://github.com/Strumenta/starlasu-lionweb-repository-client/tree/feature/nodeIdCalculation) `adjustSource` is being removed

**Comment by alessiostalla** [comment]
I think we can close this
