### ISSUE TITLE
Initialize the DB

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/starlasu-lionweb-repository-client#8]
During development, we connect to a freshly provisioned model repository pointing to an empty DB. In that scenario, we have to initialize the DB before using it:

```kotlin
    val url = "http://${client.hostname}:${client.port}/init"
    val request: Request = Request.Builder()
        .url(url)
        .post("".toRequestBody())
        .build()
    OkHttpClient().newCall(request).execute().use { response ->
        if (response.code == 200) {
            println("DB initialized")
        } else {
            println("DB initialization failed, HTTP ${response.code}: ${response.body?.string()}")
        }
    }
```

It would be useful if the client came with this built into a method one can call for testing, at least for now. Although ideally the model-repo should init itself at startup.

**Comment by ftomassetti** [comment]
I created an issue in the LionWeb repository: https://github.com/LionWeb-io/lionweb-repository/issues/31

**Comment by ftomassetti** [comment]
In the meantime, I will add this method, as requested
